title: b14ckb0x's space
description: Hack everything

pagination:
  enabled: true
  per_page: 5
  permalink: "/page:num/"
  sort_field: "date"
  sort_reverse: true

autopages:
  enabled: true
  categories:
    enabled: true
    layouts:
      - category.html
    permalink: "/category/:cat/"
  tags:
    enabled: false
  collections:
    enabled: false

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap